version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1p9jpiacev5el"
s3_prefix = "hello-world-aws"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
